builders:
  edgeql_codegen:
    import: "package:gel/edgeql_codegen.dart"
    builder_factories: ["edgeqlCodegenBuilder"]
    build_extensions: { ".edgeql": [".edgeql.dart", ".edgeql.debug"] }
    build_to: source
    auto_apply: dependents
