name: gel
description: |
  Official Dart client library for Gel, a database built on Postgres with a
  modern data model, graph queries, built-in Auth & AI solutions, and more.
version: 0.6.0
homepage: https://www.geldata.com
repository: https://github.com/geldata/gel-dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  path: ^1.8.2
  build: ^2.3.0
  code_builder: ^4.2.0
  dart_style: ^3.0.1
  pub_semver: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  html: ^0.15.4
  args: ^2.4.2
